// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v1.0.0
// source: github.com/kralicky/jobserver/pkg/apis/job/v1/job.proto

package v1

import (
	_ "github.com/kralicky/jobserver/pkg/apis/rbac/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State describes the logical state of a job.
//
//	┌─────────────────────────────────────────┐
//	│                                         │
//	│              ┌────────┐                 │
//	│      ┌──────►│ Failed │                 │
//	│      │       └────────┘                 │
//	│ ┌────┴────┐              ┌────────────┐ │
//	│ │ Pending │              │ Terminated │ │
//	│ └────┬────┘              └────────────┘ │
//	│      │       ┌─────────┐        ▲       │
//	│      └──────►│ Running ├────────┘       │
//	│              └─────────┘                │
//	│                                         │
//	└─────────────────────────────────────────┘
type State int32

const (
	State_Unknown State = 0
	// The job is waiting to be started, and is not yet running.
	State_Pending State = 1
	// The job failed to start.
	State_Failed State = 2
	// The job started successfully and is currently running.
	State_Running State = 3
	// The job is no longer running.
	State_Terminated State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "Unknown",
		1: "Pending",
		2: "Failed",
		3: "Running",
		4: "Terminated",
	}
	State_value = map[string]int32{
		"Unknown":    0,
		"Pending":    1,
		"Failed":     2,
		"Running":    3,
		"Terminated": 4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{0}
}

// JobSpec describes a command to be run, along with optional resource limits
// that should be applied to the command's process.
type JobSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command *CommandSpec    `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Limits  *ResourceLimits `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobSpec) GetCommand() *CommandSpec {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *JobSpec) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type JobId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JobId) Reset() {
	*x = JobId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobId) ProtoMessage() {}

func (x *JobId) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobId.ProtoReflect.Descriptor instead.
func (*JobId) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JobIdList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*JobId `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *JobIdList) Reset() {
	*x = JobIdList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobIdList) ProtoMessage() {}

func (x *JobIdList) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobIdList.ProtoReflect.Descriptor instead.
func (*JobIdList) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *JobIdList) GetItems() []*JobId {
	if x != nil {
		return x.Items
	}
	return nil
}

type JobStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The job's logical state.
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=job.v1.State" json:"state,omitempty"`
	// The job's original spec.
	Spec *JobSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// A human-readable message describing the job's state, or an error message
	// if the job failed.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// The PID of the job's process. Only present if the job is in the Running
	// or Terminated state.
	Pid int32 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	// The time at which the job was started. Only present if the job is
	// in the Running or Terminated state.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// Termination details. Only present if the job is in the Terminated state.
	Terminated *TerminationStatus `protobuf:"bytes,6,opt,name=terminated,proto3" json:"terminated,omitempty"`
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatus) GetState() State {
	if x != nil {
		return x.State
	}
	return State_Unknown
}

func (x *JobStatus) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *JobStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *JobStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *JobStatus) GetTerminated() *TerminationStatus {
	if x != nil {
		return x.Terminated
	}
	return nil
}

// Contains details about the cause of the process's termination.
type TerminationStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If the process exited normally, this will contain its exit code. Otherwise,
	// if it was terminated by a signal, it will not be present.
	ExitCode *int32 `protobuf:"varint,1,opt,name=exitCode,proto3,oneof" json:"exitCode,omitempty"`
	// If the process was terminated by a signal, this will contain the signal
	// number. Otherwise, it will not be present.
	Signal *int32 `protobuf:"varint,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	// If the process was stopped by the user with the Stop() method, this will
	// be true. Otherwise, it will be false.
	Stopped bool `protobuf:"varint,3,opt,name=stopped,proto3" json:"stopped,omitempty"`
	// The time at which the process was terminated.
	Time *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TerminationStatus) Reset() {
	*x = TerminationStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminationStatus) ProtoMessage() {}

func (x *TerminationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminationStatus.ProtoReflect.Descriptor instead.
func (*TerminationStatus) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *TerminationStatus) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *TerminationStatus) GetSignal() int32 {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return 0
}

func (x *TerminationStatus) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *TerminationStatus) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type CommandSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The command name to run. Required.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// The command's arguments, not containing the command name itself.
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// Optional additional environment variables to set for the command.
	// These will be merged with the job server's environment variables.
	Env []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *CommandSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandSpec) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ProcessOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A chunk of output from the process's combined stdout and stderr streams.
	//
	// This is a raw byte stream, and may contain arbitrary binary data,
	// depending on the command being run. It is up to the client to interpret
	// the output correctly based on the command being run. No guarantees are
	// made about the size of each chunk, or the frequency at which they
	// are sent.
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ProcessOutput) Reset() {
	*x = ProcessOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOutput) ProtoMessage() {}

func (x *ProcessOutput) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOutput.ProtoReflect.Descriptor instead.
func (*ProcessOutput) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessOutput) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type ResourceLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Process CPU limit defined in milli-cores (1000 = 1 core/vcpu)
	Cpu *int64 `protobuf:"varint,1,opt,name=cpu,proto3,oneof" json:"cpu,omitempty"`
	// Process memory limit defined in bytes
	Memory *MemoryLimits `protobuf:"bytes,2,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
	// Process IO limits for storage devices
	Io []*IODeviceLimits `protobuf:"bytes,3,rep,name=io,proto3" json:"io,omitempty"`
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceLimits) GetCpu() int64 {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return 0
}

func (x *ResourceLimits) GetMemory() *MemoryLimits {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ResourceLimits) GetIo() []*IODeviceLimits {
	if x != nil {
		return x.Io
	}
	return nil
}

type MemoryLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Memory soft limit defined in bytes. Processes exceeding the limit are
	// not OOM-killed, but may be throttled by the kernel.
	SoftLimit *int64 `protobuf:"varint,1,opt,name=softLimit,proto3,oneof" json:"softLimit,omitempty"`
	// Memory limit defined in bytes. If exceeded, the process will be OOM-killed.
	Limit *int64 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *MemoryLimits) Reset() {
	*x = MemoryLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryLimits) ProtoMessage() {}

func (x *MemoryLimits) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryLimits.ProtoReflect.Descriptor instead.
func (*MemoryLimits) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryLimits) GetSoftLimit() int64 {
	if x != nil && x.SoftLimit != nil {
		return *x.SoftLimit
	}
	return 0
}

func (x *MemoryLimits) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type IODeviceLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Device path (e.g. /dev/sda)
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// Limits for the device
	Limits *IOLimits `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *IODeviceLimits) Reset() {
	*x = IODeviceLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IODeviceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IODeviceLimits) ProtoMessage() {}

func (x *IODeviceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IODeviceLimits.ProtoReflect.Descriptor instead.
func (*IODeviceLimits) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{9}
}

func (x *IODeviceLimits) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *IODeviceLimits) GetLimits() *IOLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type IOLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Limit for read operations in bytes per second
	ReadBps *int64 `protobuf:"varint,2,opt,name=readBps,proto3,oneof" json:"readBps,omitempty"`
	// Limit for write operations in bytes per second
	WriteBps *int64 `protobuf:"varint,3,opt,name=writeBps,proto3,oneof" json:"writeBps,omitempty"`
	// Limit for read operations in IOPS
	ReadIops *int64 `protobuf:"varint,4,opt,name=readIops,proto3,oneof" json:"readIops,omitempty"`
	// Limit for write operations in IOPS
	WriteIops *int64 `protobuf:"varint,5,opt,name=writeIops,proto3,oneof" json:"writeIops,omitempty"`
}

func (x *IOLimits) Reset() {
	*x = IOLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IOLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOLimits) ProtoMessage() {}

func (x *IOLimits) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOLimits.ProtoReflect.Descriptor instead.
func (*IOLimits) Descriptor() ([]byte, []int) {
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP(), []int{10}
}

func (x *IOLimits) GetReadBps() int64 {
	if x != nil && x.ReadBps != nil {
		return *x.ReadBps
	}
	return 0
}

func (x *IOLimits) GetWriteBps() int64 {
	if x != nil && x.WriteBps != nil {
		return *x.WriteBps
	}
	return 0
}

func (x *IOLimits) GetReadIops() int64 {
	if x != nil && x.ReadIops != nil {
		return *x.ReadIops
	}
	return 0
}

func (x *IOLimits) GetWriteIops() int64 {
	if x != nil && x.WriteIops != nil {
		return *x.WriteIops
	}
	return 0
}

var File_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto protoreflect.FileDescriptor

var file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDesc = []byte{
	0x0a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61,
	0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x2f,
	0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6a, 0x6f, 0x62, 0x2e, 0x76,
	0x31, 0x1a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72,
	0x61, 0x6c, 0x69, 0x63, 0x6b, 0x79, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x07, 0x4a, 0x6f,
	0x62, 0x53, 0x70, 0x65, 0x63, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x06, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x73, 0x22, 0x17, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a,
	0x09, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6a, 0x6f, 0x62, 0x2e,
	0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0xf6, 0x01, 0x0a, 0x09, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x6a,
	0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x70, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x39, 0x0a,
	0x0a, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x74, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f,
	0x0a, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x4d,
	0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x76, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0x27, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x15, 0x0a, 0x03, 0x63, 0x70, 0x75,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x63, 0x70, 0x75, 0x88, 0x01, 0x01,
	0x12, 0x31, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x48, 0x01, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4f, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x02, 0x69, 0x6f, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x63, 0x70, 0x75, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22, 0x64,
	0x0a, 0x0c, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x21,
	0x0a, 0x09, 0x73, 0x6f, 0x66, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x09, 0x73, 0x6f, 0x66, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x73, 0x6f, 0x66, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x52, 0x0a, 0x0e, 0x49, 0x4f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x4f, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73,
	0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x08, 0x49, 0x4f, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x42, 0x70, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x42, 0x70,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42, 0x70, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x70, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x49, 0x6f, 0x70,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x49,
	0x6f, 0x70, 0x73, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x49,
	0x6f, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x09, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x49, 0x6f, 0x70, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x72, 0x65,
	0x61, 0x64, 0x42, 0x70, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x70, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x49, 0x6f, 0x70, 0x73, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x49, 0x6f, 0x70, 0x73, 0x2a, 0x4a, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x10, 0x04, 0x32, 0x8e, 0x02, 0x0a, 0x03, 0x4a, 0x6f,
	0x62, 0x12, 0x27, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x0f, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x70, 0x65, 0x63, 0x1a, 0x0d, 0x2e, 0x6a, 0x6f,
	0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x04, 0x53, 0x74,
	0x6f, 0x70, 0x12, 0x0d, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x49,
	0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x06, 0x8a, 0xe2, 0x09, 0x02, 0x08,
	0x01, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x2e, 0x6a, 0x6f,
	0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x1a, 0x11, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x06, 0x8a,
	0xe2, 0x09, 0x02, 0x08, 0x01, 0x12, 0x39, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4a,
	0x6f, 0x62, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x06, 0x8a, 0xe2, 0x09, 0x02, 0x08, 0x01,
	0x12, 0x38, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x6a, 0x6f, 0x62, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x22, 0x06, 0x8a, 0xe2, 0x09, 0x02, 0x08, 0x01, 0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x6c, 0x69, 0x63, 0x6b,
	0x79, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x73, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescOnce sync.Once
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescData = file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDesc
)

func file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescGZIP() []byte {
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescOnce.Do(func() {
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescData)
	})
	return file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDescData
}

var file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_goTypes = []interface{}{
	(State)(0),                    // 0: job.v1.State
	(*JobSpec)(nil),               // 1: job.v1.JobSpec
	(*JobId)(nil),                 // 2: job.v1.JobId
	(*JobIdList)(nil),             // 3: job.v1.JobIdList
	(*JobStatus)(nil),             // 4: job.v1.JobStatus
	(*TerminationStatus)(nil),     // 5: job.v1.TerminationStatus
	(*CommandSpec)(nil),           // 6: job.v1.CommandSpec
	(*ProcessOutput)(nil),         // 7: job.v1.ProcessOutput
	(*ResourceLimits)(nil),        // 8: job.v1.ResourceLimits
	(*MemoryLimits)(nil),          // 9: job.v1.MemoryLimits
	(*IODeviceLimits)(nil),        // 10: job.v1.IODeviceLimits
	(*IOLimits)(nil),              // 11: job.v1.IOLimits
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_depIdxs = []int32{
	6,  // 0: job.v1.JobSpec.command:type_name -> job.v1.CommandSpec
	8,  // 1: job.v1.JobSpec.limits:type_name -> job.v1.ResourceLimits
	2,  // 2: job.v1.JobIdList.items:type_name -> job.v1.JobId
	0,  // 3: job.v1.JobStatus.state:type_name -> job.v1.State
	1,  // 4: job.v1.JobStatus.spec:type_name -> job.v1.JobSpec
	12, // 5: job.v1.JobStatus.startTime:type_name -> google.protobuf.Timestamp
	5,  // 6: job.v1.JobStatus.terminated:type_name -> job.v1.TerminationStatus
	12, // 7: job.v1.TerminationStatus.time:type_name -> google.protobuf.Timestamp
	9,  // 8: job.v1.ResourceLimits.memory:type_name -> job.v1.MemoryLimits
	10, // 9: job.v1.ResourceLimits.io:type_name -> job.v1.IODeviceLimits
	11, // 10: job.v1.IODeviceLimits.limits:type_name -> job.v1.IOLimits
	1,  // 11: job.v1.Job.Start:input_type -> job.v1.JobSpec
	2,  // 12: job.v1.Job.Stop:input_type -> job.v1.JobId
	2,  // 13: job.v1.Job.Status:input_type -> job.v1.JobId
	13, // 14: job.v1.Job.List:input_type -> google.protobuf.Empty
	2,  // 15: job.v1.Job.Output:input_type -> job.v1.JobId
	2,  // 16: job.v1.Job.Start:output_type -> job.v1.JobId
	13, // 17: job.v1.Job.Stop:output_type -> google.protobuf.Empty
	4,  // 18: job.v1.Job.Status:output_type -> job.v1.JobStatus
	3,  // 19: job.v1.Job.List:output_type -> job.v1.JobIdList
	7,  // 20: job.v1.Job.Output:output_type -> job.v1.ProcessOutput
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_init() }
func file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_init() {
	if File_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobIdList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminationStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IODeviceLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IOLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_goTypes,
		DependencyIndexes: file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_depIdxs,
		EnumInfos:         file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_enumTypes,
		MessageInfos:      file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_msgTypes,
	}.Build()
	File_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto = out.File
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_rawDesc = nil
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_goTypes = nil
	file_github_com_kralicky_jobserver_pkg_apis_job_v1_job_proto_depIdxs = nil
}
